/**
 * Fetches the OpenAPI spec from the Chatterbox TTS API and generates TypeScript types.
 *
 * Usage:
 *   CHATTERBOX_API_URL=https://your-api-url npm run sync-api
 *
 * Or with .env file:
 *   npm run sync-api
 */

// Import file system utilities for reading and writing files
import fs from "node:fs";
// Import path utilities for working with file paths
import path from "node:path";
// Import fileURLToPath to convert import.meta.url to a file path
import { fileURLToPath } from "node:url";

// Load environment variables from .env file
import "dotenv/config";
// Import the openapi-typescript library to generate TypeScript types from OpenAPI specs
import openapiTS, { astToString } from "openapi-typescript";

// Get the directory name of the current script using ES module conventions
const __dirname = path.dirname(fileURLToPath(import.meta.url));
// Define the output path for the generated TypeScript types definition file
const OUTPUT_PATH = path.resolve(__dirname, "../src/types/chatterbox-api.d.ts");

/**
 * Main async function that orchestrates the API sync process:
 * 1. Retrieves the API URL from environment variables
 * 2. Fetches the OpenAPI spec from the API endpoint
 * 3. Generates TypeScript types from the OpenAPI spec
 * 4. Writes the generated types to a file with appropriate headers
 */
async function main() {
  // Retrieve the Chatterbox API URL from environment variables
  const apiUrl = process.env.CHATTERBOX_API_URL;

  // Validate that the required environment variable is set
  if (!apiUrl) {
    console.error("Error: CHATTERBOX_API_URL environment variable is required");
    process.exit(1);
  }

  // Construct the full URL to the OpenAPI specification JSON file
  const openApiUrl = `${apiUrl}/openapi.json`;
  console.log(`Fetching OpenAPI spec from: ${openApiUrl}`);

  // Fetch the OpenAPI spec and convert it to an Abstract Syntax Tree (AST)
  const ast = await openapiTS(new URL(openApiUrl));
  // Convert the AST to a formatted TypeScript string
  const contents = astToString(ast);

  // Extract the directory path from the output file path
  const outputDir = path.dirname(OUTPUT_PATH);
  // Check if the output directory exists; create it recursively if it doesn't
  if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true });
  }

  // Construct a header comment that will be prepended to the generated types file
  // This header includes metadata about the auto-generation and the source OpenAPI URL
  const header = `/**
* This file is auto-generated by scripts/sync-api.ts
* Do not edit manually. Run \`npm run sync-api\` to regenerate.
*
* Generated from: ${openApiUrl}
* Generated at: ${new Date().toISOString()}
*/
  `;

  // Write the header and generated TypeScript types to the output file
  fs.writeFileSync(OUTPUT_PATH, header + contents);
  // Log the successful completion of the operation
  console.log(`Types written to: ${OUTPUT_PATH}`);
}

// Execute the main function and handle any errors that occur during execution
main().catch((err) => {
  console.error("Failed to sync API types:", err);
  process.exit(1);
});
